apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-deployment
spec:
  replicas: 2
  selector: 
    matchLables:
      app: cafe 
  template:
    metadata:
      labels: 
        app: cafe
    spec:
      containers:
      - name: cafe-deployment
        image: vishakhagujar/ci-cd_setup_demo:latest
        ports:
        - containerPort: 80
    
